# Generated by Django 3.2.25 on 2024-11-12 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('recipe_ingredients', models.TextField(verbose_name='Ingredients')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('nutrition_info', models.JSONField(blank=True, null=True, verbose_name='Nutrition Info')),
                ('preparation_time', models.IntegerField(blank=True, null=True, verbose_name='Preparation Time (minutes)')),
                ('suitable_weather', models.CharField(blank=True, max_length=50, verbose_name='Suitable Weather')),
                ('mood', models.CharField(blank=True, max_length=50, verbose_name='Mood')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Cost (yen)')),
                ('serving_size', models.IntegerField(blank=True, null=True, verbose_name='Serving Size')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
