# Generated by Django 3.2.25 on 2024-11-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='serving_size',
            new_name='num_people',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutrition_info',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='suitable_weather',
        ),
        migrations.AddField(
            model_name='recipe',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Budget (NTD)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Recipe Info'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_ingredients',
            field=models.TextField(blank=True, verbose_name='User Ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='weather',
            field=models.CharField(blank=True, max_length=50, verbose_name='Weather'),
        ),
    ]
