# Generated by Django 3.2.25 on 2024-11-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_info',
            field=models.TextField(blank=True, null=True, verbose_name='Recipe Info'),
        ),
    ]
