# Generated by Django 3.2.25 on 2024-11-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='num_people',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='recipe_info',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='user_ingredients',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='weather',
        ),
        migrations.AddField(
            model_name='diary',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Recipe'),
        ),
    ]
