# Generated by Django 3.2.25 on 2025-01-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(default=False, help_text='Indicates whether the user profile is visible to others.', verbose_name='Is profile public?'),
        ),
    ]
